name: Build Binaries

on:
  pull_request:
    branches: [ "master" ]

env:
  GO_VERSION: '1.22'
  CGO_ENABLED: 1

jobs:
  build:
    runs-on: fyneio/fyne-cross
    strategy:
      matrix:
        os: [ windows ]
        arch: [ amd64 ]
        cc: [ x86_64-w64-mingw64-gcc ]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5
        env:
          ImageOS: ${{ matrix.os }}-${{ matrix.arch }}
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          CC: ${{ matrix.cc }}
        run: go build
